#!/usr/bin/env bash
#Transfer files from from client to server
if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_FILE IP USENAME PATH_TO_SSH_KEY"
	exit 1
fi
FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY_PATH=$4
scp -i "$SSH_KEY_PATH" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"
if [ $? -eq O ]; then
	echo "File transferred successfully"
else
	echo "File transfer failed"
	exit
fi
