#!usr/bin/env bash
# SSH client configuration
Host *
    User ubuntu
    PasswordAuthentication no
    IdentityFile ~/.ssh/school
    sendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    HostName 100.26.152.208
