#!usr/bin/env bash
# SSH client configuration
Host *
    PasswordAuthentication no
    IdentityFile ~/.ssh/school
    sendEnv LAN LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
